physDict = {
    "NOM_ECG_V_P_C_CNT": " ",
    "NOM_ECG_TIME_PD_QT_GL": " ",
    "NOM_ECG_TIME_PD_QTc": " ",
    "NOM_ECG_TIME_PD_QTc_DELTA": " ",
    "NOM_ECG_TIME_PD_QT_HEART_RATE": " ",
    "ETCO2": " ",
    "64052": " ",
    "UID": " ",
    "timestamp": " ",
    "SPO2": " ",
    "4822": " ",
    "4BB0": " ",
    "HR": " ",
    "RR": " ",
    "NOM_ECG_AMPL_ST_I": " ",
    "NOM_ECG_AMPL_ST_II": " ",
    "NOM_ECG_AMPL_ST_AVF": " ",
    "UID": " ",
    "timestamp": "1689615271083",
    "BP_SYS": " ",
    "BP_DIA": " ",
    "BP": " ",
    "F0E5": " ",
    "UID": " ",
    "timestamp": " ",
}

settDict = {
    "VtID": " ",
    "Type": " ",
    "Mode": " ",
    "SetRate": " ",
    "SetVT": " ",
    "SetFlow": " ",
    "SetFIO2": " ",
    "SetPEEP": " ",
    "SetPSV": " ",
    "SetP": " ",
    "SetTi": " ",
    "UID": " ",
    "timestamp": " ",
}

vitDict = {
    "Pplat": " ",
    "TotBrRate": " ",
    "VTe": " ",
    "MinVent": " ",
    "PIP": " ",
    "Ti": " ",
    "VTi": " ",
    "PEEPi": " ",
    "RSBI": " ",
    "TiTtot": " ",
    "PEEP": " ",
    "Raw": " ",
    "NIF": " ",
    "UID": " ",
    "timestamp": " ",
}

csvFiles = {"physFile": "phys_", "settFile": "sett_", "vitFile": "vit_"}
csvHeaders = {
    "physHeader": "phys_Header.csv",
    "settHeader": "sett_Header.csv",
    "vitHeader": "vit_Header.csv",
}
